### PR TITLE
Check reviewer permissions in resolvers / check session in review page

### LINKED ISSUE #268: [Feature] - Make sure student has proper permissions to review student submissions
1. If someone did not pass a lesson, they should not be able to see submissions. - Add a check to getSubmission resolver, approve / reject mutation.

Create a helper function `hasPassedLesson(lessonId)`

### LINKED ISSUE #395: [Bug] Review page does not check if user is logged in
When going directly to the submissions review page from a link in the chat, the user is not verified if it's logged in. This leads to an silent `Invalid user` error from graphql when sending a submission review if the user does not login, found only by checking the network requests in the developer console.

The page should redirect the user to login when accessed without being logged in, or show a detailed error message to the user when trying to submit a review.

Sample error from the developer console:

```js
{
  "errors": [
    {
      "message": "Error: Invalid user",
      "locations": [{ "line": 2, "column": 3 }],
      "path": ["rejectSubmission"],
      "extensions": { "code": "INTERNAL_SERVER_ERROR" }
    }
  ],
  "data": { "rejectSubmission": null }
}
```

### PR DESCRIPTION
**Pull request by ggwadera**
closes #268 
closes #395 

This PR:

- adds a new helper function `hasPassedLesson(reviewerId, lessonId)` to check if the reviewing user has completed the lesson;
- adds checks to submission resolvers to verify if user has completed the lesson before doing the query/mutation;
- refactors submission resolvers that had repeated code with a `getReviewer(context, lessonId)` that does the checks on the user and returns the `reviewerId`
- adds `lessonId` to the `SubmissionData` and `ArgsUpdateSubmission` types, used in the new helper function;
- adds a redirect to the login page when there's no user session on the review page;
- adds/fixes tests for the new and modified functions.

### CODE REVIEW

File: components/ReviewCard.tsx [hunk 1]
```diff
@@ -85,6 +86,7 @@ export const ReviewCard: React.FC<ReviewCardProps> = ({ submissionData }) => {
     await review({
       variables: {
         submissionId: id,
+        lessonId: lessonId,
```
Comment (anthonykhoa) [inline components/ReviewCard.tsx:89]: Can this be destructured? From `lessonId: lessonId,` to `'lessonId,`

Comment (ggwadera) [reply components/ReviewCard.tsx]: Done!

File: pages/review/[lesson].tsx [hunk 2]
```diff
@@ -39,10 +39,16 @@ const Review: React.FC<QueryDataProps<AppData>> = ({ queryData }) => {
...
+  if (!session) {
+    router.push('/login')
+    return null
+  }
+  const lessonSubmissions: SubmissionData[] = data
+    ? data.submissions.filter(
+        (submission: SubmissionData) =>
+          submission.status !== 'passed' && submission.status !== 'needMoreWork'
+      )
+    : ([] as SubmissionData[])
```
Comment (anthonykhoa) [inline pages/review/[lesson].tsx:51]: `[] as SubmissionData[]` to `[]`

**Review by anthonykhoa — APPROVED** [review]

**Review by anthonykhoa — APPROVED** [review]

**Review by songz — APPROVED** [review]
