### PR TITLE
bug: Revert setting password from signup page

### LINKED ISSUE #2233: Email verification is sent even though the user had set their password
Adding a desc soon-

### PR DESCRIPTION
**Pull request by flacial**
Closes #2233 

# Problem

In a recent [PR](https://github.com/garageScript/c0d3-app/pull/2121), we [added the password input to the signup page](https://github.com/garageScript/c0d3-app/pull/2121/files?diff=unified&w=0#diff-ec19229a2116827f3547fc5388a076f79fd79ed52d5a6208ef8a344efd990602R107) in order to send all the user auth data in one request to next-auth credentials provider. 

It worked fine, but we forgot that we've email verification in place and the user sets a password after they click the link in the email sent to them.

Currently when the user signup, they set their password and an email is sent to them *to set their password again*.

# Solution

Revert the changes from the origin PR:
- [Remove the password field from the signup page](https://github.com/garageScript/c0d3-app/pull/2234/files#diff-ec19229a2116827f3547fc5388a076f79fd79ed52d5a6208ef8a344efd990602L107-L113)
- [Update the signup resolver to not take and set a password for the user](https://github.com/garageScript/c0d3-app/pull/2234/files#diff-28c059a65538dc09013d8b18dcdb5ab46a6f8c5119b0948e3e4bf98e126ef240L99)
- [Update the next-auth credentials provider to not pass a password to the signup resolver](https://github.com/garageScript/c0d3-app/pull/2234/files#diff-8141f1721333720484175de71829bce641bf7f508299a2d48dd5177f3288d763L38)

Fixed issues:
- [Stop authorizing users in the signup resolver before they verify the email](https://github.com/garageScript/c0d3-app/pull/2234/files#diff-28c059a65538dc09013d8b18dcdb5ab46a6f8c5119b0948e3e4bf98e126ef240L182)
- After the user _signup_, a button shows up that direct them to *set the password* password. Update what's supposed to be shown to the following:
image

# Changes need to be done after merging this PR

Update this the [last next-auth PR](https://github.com/garageScript/c0d3-app/pull/1985) to handle email verification by following this [comment](https://github.com/nextauthjs/next-auth/discussions/3478)

### CODE REVIEW

File: graphql/typeDefs.ts [hunk 1]
```diff
@@ -31,8 +31,7 @@ export default gql`
       firstName: String!
       lastName: String!
       email: String!
-      username: String!
-      password: String!
+      username: String! # password: String!
```
Comment (bryanjenningz) [inline graphql/typeDefs.ts:34]: Did you mean to leave this comment?

File: pages/signup.tsx [hunk 2]
```diff
@@ -156,7 +165,8 @@ const SignUpPage: React.FC<GetAppProps> & WithLayout = ({
     try {
       const { data } = await signupUser({ variables: values })
       if (data.signup.success) {
-        return router.push('/curriculum')
+        setForgotToken(data.signup.cliToken)
```
Comment (bryanjenningz) [inline pages/signup.tsx:168]: Is it possible for data.signup.cliToken to be null at this point?

**Review by bryanjenningz — APPROVED** [review]

File: graphql/typeDefs.ts (hunk 1 above)
Comment (flacial) [reply graphql/typeDefs.ts:34]: Oops, dead code.

**Review by bryanjenningz — APPROVED** [review]

**Review by SlyBouhafs — APPROVED** [review]

**Review by songz — APPROVED** [review]
