### PR TITLE
close #883 - fix element overlapping on mobile devices

### LINKED ISSUE #883: Lesson title and "completed" element ovelap on mobile devices
There isn't enough space for a full title so you end up with something like "Founda completed tions of javascript"

overlap

It works fine on Firefox but not on Chrome.

### PR DESCRIPTION
**Pull request by Ulisseus**
Simple css fix to prevent overlapping in chromium based browsers.

Currently "completed" badge and review button are floats. This PR changes display of their parent to flex-column on small devices (smaller than md bootsrap breakpoint of 768px). Desktop layout should be the same. 

Before:
overlap

After:
noOverlap

[Vercel](https://c0d3-app-35b6c1ucd-c0d3.vercel.app/)

### CODE REVIEW

**Comment by hwong0305** [comment]
Instead of creating whitespace to allow mobile to view the full badge, is it possible to shrink the badge on the mobile version to just the icon?

**Review by kondanna — APPROVED** [review]

**Review by ggwadera — APPROVED** [review]

File: components/LessonCard.tsx [hunk 1]
```diff
@@ -73,9 +73,11 @@ const LessonCard: React.FC<Props> = props => {
...
 
-        <div className={`${styles['lesson-card__description']} pl-4`}>
+        <div
+          className={`${styles['lesson-card__description']} pl-4 d-flex flex-column d-md-block`}
+        >
           {props.currentState === 'completed' && (
-            <span className="badge badge-pill badge-success float-right mt-2 mr-2 p-2 d-flex align-items-center">
+            <span className="badge badge-pill badge-success float-right align-self-end mt-2 mr-2 p-2 d-flex align-items-center">
               <CheckCircle style={{ height: '15px' }} />
               <span className="mx-1">COMPLETED</span>
```
Comment (JasirZaeem) [inline components/LessonCard.tsx:82]: Bootstrap utilities like 
`<span className="mx-1 d-none d-md-inline">COMPLETED</span>`
Can be used to hide this and only leave the check on smaller screen
image

**Review by JasirZaeem — APPROVED** [review]

**Comment by Ulisseus** [comment]
Updated:
* Desktop css should be pretty much the same 
* On mobile devices "completed" button becomes smaller green check
* On very small devices lesson images are hidden
