### PR TITLE
close #248 - lesson card should take users to the correct url

### LINKED ISSUE #248: Bug - Review lesson card takes users to the wrong url

### PR DESCRIPTION
**Pull request by stevenlay**
Currently, when a user clicks on the link to go review challenge submissions once they have completed all of the challenges for a section, they are brought to a 404 error for page not found. 
image

The correction redirects the user to the appropriate URL by fixing the link.

### CODE REVIEW

File: components/ChallengeMaterial.tsx [hunk 1]
```diff
@@ -358,7 +358,7 @@ const ChallengeMaterial: React.FC<ChallengeMaterialProps> = ({
           <ChallengesCompletedCard
             imageSrc="icon-challenge-complete.jpg"
             chatUrl={chatUrl}
-            reviewUrl={`https:/c0d3.com/teacher/${lessonId}`}
+            reviewUrl={`https://c0d3.com/teacher/${lessonId}`}
```
Comment (songz) [inline components/ChallengeMaterial.tsx:361]: `https://www.c0d3.com/review/${lessonId}` -> teacher route is deprecated, thanks

Comment (stevenlay) [reply components/ChallengeMaterial.tsx]: updated to use review route
